version: '3.8'

services:
  web:
    build: .
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run cmd/server.go
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5440:5432"
    volumes:
      - logicloud-data:/var/lib/postgres/data
volumes:
  logicloud-data: