package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"backend/graph/generated"
	"backend/graph/model"
	"context"
	"fmt"
)

// Resend is the resolver for the resend field.
func (r *resendOtpMutationResolver) Resend(ctx context.Context, obj *model.ResendOtpMutation) (*model.OtpMutationResponse, error) {
	panic(fmt.Errorf("not implemented: Resend - resend"))
}

// ResendOtpMutation returns generated.ResendOtpMutationResolver implementation.
func (r *Resolver) ResendOtpMutation() generated.ResendOtpMutationResolver {
	return &resendOtpMutationResolver{r}
}

type resendOtpMutationResolver struct{ *Resolver }
