package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"backend/graph/generated"
	"backend/graph/model"
	"context"
)

// Resend is the resolver for the resend field.
func (r *resendOtpMutationResolver) Resend(ctx context.Context, obj *model.ResendOtpMutation, input model.ResendOtpInput) (*model.OtpMutationResponse, error) {
	return r.AuthDomain.UpdateOtp(ctx, &input.UserID), nil
}

// VerifyOtp is the resolver for the verifyOtp field.
func (r *resendOtpMutationResolver) VerifyOtp(ctx context.Context, obj *model.ResendOtpMutation, input model.VerifyOtpInput) (*model.OtpMutationResponse, error) {
	return r.AuthDomain.VerifyOtp(ctx, &input), nil
}

// ResendOtpMutation returns generated.ResendOtpMutationResolver implementation.
func (r *Resolver) ResendOtpMutation() generated.ResendOtpMutationResolver {
	return &resendOtpMutationResolver{r}
}

type resendOtpMutationResolver struct{ *Resolver }
