package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"backend/graph/generated"
	"backend/graph/model"
	"context"
	"fmt"
)

// CreateProduct is the resolver for the createProduct field.
func (r *productMutationResolver) CreateProduct(ctx context.Context, obj *model.ProductMutation, input model.CreateProductInput) (*model.ProductMutationResponse, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *productMutationResolver) UpdateProduct(ctx context.Context, obj *model.ProductMutation, input model.UpdateProductInput) (*model.ProductMutationResponse, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *productMutationResolver) DeleteProduct(ctx context.Context, obj *model.ProductMutation, input model.DeleteProductInput) (*model.ProductMutationResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteProduct - deleteProduct"))
}

// GetProductsByFilter is the resolver for the getProductsByFilter field.
func (r *productQueryResolver) GetProductsByFilter(ctx context.Context, obj *model.ProductQuery, input model.GetProductsByFilterInput) (*model.ProductsQueryResponse, error) {
	panic(fmt.Errorf("not implemented: GetProductsByFilter - getProductsByFilter"))
}

// GetProductByID is the resolver for the getProductByID field.
func (r *productQueryResolver) GetProductByID(ctx context.Context, obj *model.ProductQuery, input model.GetProductByIDInput) (*model.ProductQueryResponse, error) {
	panic(fmt.Errorf("not implemented: GetProductByID - getProductByID"))
}

// ProductMutation returns generated.ProductMutationResolver implementation.
func (r *Resolver) ProductMutation() generated.ProductMutationResolver {
	return &productMutationResolver{r}
}

// ProductQuery returns generated.ProductQueryResolver implementation.
func (r *Resolver) ProductQuery() generated.ProductQueryResolver { return &productQueryResolver{r} }

type productMutationResolver struct{ *Resolver }
type productQueryResolver struct{ *Resolver }
