package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"backend/graph/generated"
	"backend/graph/model"
	"context"
	"fmt"
)

// Product is the resolver for the product field.
func (r *salesResolver) Product(ctx context.Context, obj *model.Sales) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: Product - product"))
}

// Organization is the resolver for the organization field.
func (r *salesResolver) Organization(ctx context.Context, obj *model.Sales) (*model.Organization, error) {
	panic(fmt.Errorf("not implemented: Organization - organization"))
}

// SoldBy is the resolver for the soldBy field.
func (r *salesResolver) SoldBy(ctx context.Context, obj *model.Sales) (*model.User, error) {
	panic(fmt.Errorf("not implemented: SoldBy - soldBy"))
}

// Sales returns generated.SalesResolver implementation.
func (r *Resolver) Sales() generated.SalesResolver { return &salesResolver{r} }

type salesResolver struct{ *Resolver }
