package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"backend/graph/generated"
	"backend/graph/model"
	"context"
	"fmt"
)

// CreateUser is the resolver for the createUser field.
func (r *userMutationResolver) CreateUser(ctx context.Context, obj *model.UserMutation, input model.UserInput) (*model.AuthMutationResponse, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// GetAllUsers is the resolver for the getAllUsers field.
func (r *userQueryResolver) GetAllUsers(ctx context.Context, obj *model.UserQuery) (*model.AuthQueryResponse, error) {
	panic(fmt.Errorf("not implemented: GetAllUsers - getAllUsers"))
}

// UserMutation returns generated.UserMutationResolver implementation.
func (r *Resolver) UserMutation() generated.UserMutationResolver { return &userMutationResolver{r} }

// UserQuery returns generated.UserQueryResolver implementation.
func (r *Resolver) UserQuery() generated.UserQueryResolver { return &userQueryResolver{r} }

type userMutationResolver struct{ *Resolver }
type userQueryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.AuthMutationResponse, error) {
	return r.AuthDomain.CreateUser(ctx, input), nil
}
